name: Tests
on:
  push:
    branches:
      - master
      - dev
    pull_request:
      branches:
      - master
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: docker compose -f tests/docker-compose.yml up
  
      
